#ifndef LORA_DEFINES_H
#define LORA_DEFINES_H

// LORA REGULATIONS
#define ETSI_EUROPE_REGULATION 1
#define FCC_US_REGULATION 2
#define SENEGAL_REGULATION 3


// LORA BANDS
#define BAND868 1
#define BAND900 2
#define BAND433 3

#endif /* Guard */
